# Generated by Django 4.2.3 on 2023-07-19 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0004_carinventory"),
    ]

    operations = [
        migrations.AddField(
            model_name="car", name="bio", field=models.TextField(blank=True, null=True),
        ),
    ]
